### ISSUE TITLE
When I Use EShop work into blazor.server,it happen a problem

### ISSUE THREAD

**Issue by LouieGuo** [EasyAbp/EShop#115]
Call store defaultasync interface circularly
![image](https://user-images.githubusercontent.com/29138525/117522151-4fbb2080-afe4-11eb-99d6-53a2be1d26f9.png)

**Comment by gdlcf88** [comment]
You may make your Host project depending on the HttpApi.Client project, check your app solution.

**Comment by LouieGuo** [comment]
已经收到您的来信，我会尽快回复。

**Comment by LouieGuo** [comment]
已经收到您的来信，我会尽快回复。
