### ISSUE TITLE
[BookingPlugin] Create

### ISSUE THREAD

**Issue by ericeric284** [EasyAbp/EShop#181]
Extention method IOrderLine.FindBookingStartingTime() will throw exception, because extra properties can not convert string to TimeSpan.
```` C#
    public static TimeSpan? FindBookingStartingTime(this IOrderLine orderLine)
    {
        //This line will fail
        return orderLine.GetProperty<TimeSpan?>(BookingOrderProperties.OrderLineBookingStartingTime);
    }
````

Step to reproduce:

1. Create entities for eshop and booking service
2. Create order and set extraProrerties (BookingOrderProperties.OrderLineBookingStartingTime) , and insert it into db
3. Get the order from db, and try to call FindBookingStartingTime();
4. Expect to get the timespan, but it will throw exception "System.InvalidCastException : Invalid cast from 'System.String' to 'System.TimeSpan'."

![image](https://user-images.githubusercontent.com/74721170/175014402-a2502a75-9893-49c8-8477-d0e992740c3e.png)

**Comment by gdlcf88** [comment]
@ericeric284 - Could you please try https://github.com/EasyAbp/EShop/commit/eaaf960139668efbd0e7a348e9d7eaf3facd7d61?

**Comment by ericeric284** [comment]
@gdlcf88 
It's working, thank you!
