### ISSUE TITLE
Duplicate option names in different attribute is not allowed

### ISSUE THREAD

**Issue by ericeric284** [EasyAbp/EShop#192]
Our team has added a car renting product, which provides attrubtes like below:

Product: Car renting service

Attibute1: "Pick up location"
Options: "Taipei","Kaohsiung","None"

Attibute2: "Return location"
Options: "Taipei","Kaohsiung","None"

But the creation of product will fail due to the check in the following code, preventing any options with duplicated names,
event if these options are under different attributes.
Is this check necessary? Or are we using it in a wrong way?

https://github.com/EasyAbp/EShop/blob/bd15d5146c0a960d08031ce761b483381e5a82cf/modules/EasyAbp.EShop.Products/src/EasyAbp.EShop.Products.Application.Contracts/EasyAbp/EShop/Products/Products/Dtos/CreateUpdateProductDto.cs#L76-L85

**Comment by gdlcf88** [comment]
@ericeric284 - I'm afraid it is a bug. Fixing. 🤣
