### ISSUE TITLE
An error occurred when switching to MySQL to generate Migration

### ISSUE THREAD

**Issue by zhangzw218** [EasyAbp/EShop#225]
I tried to run the EShopSample project.
I first in EShopSample EntityFrameworkCore, Switch to MySQL.
Then delete the original Migrations folder and run Add-migration Init.error occurred:
The foreign keys {'AssetCategoryId'} on 'AssetCategory.TimeInAdvance#TimeInAdvance' and {'ParentId'} on 'AssetCategory' are both mapped to 'EasyAbpBookingServiceAssetCategories.FK_EasyAbpBookingServiceAssetCategories_EasyAbpBookingServiceAs~', but use different columns ({'Id'} and {'ParentId'}).
……
Switch to MySQL Demo:
https://github.com/zhangzw218/EShop/tree/feature/2022092101_zzw_%E5%88%87%E6%8D%A2%E5%88%B0MySQL

**Comment by RayMMond** [comment]
@zhangzw218 

> The foreign keys {'AssetCategoryId'} on 'AssetCategory.TimeInAdvance#TimeInAdvance' and {'ParentId'} on 'AssetCategory' are both mapped to 'EasyAbpBookingServiceAssetCategories.FK_EasyAbpBookingServiceAssetCategories_EasyAbpBookingServiceAs~', but use different columns ({'Id'} and {'ParentId'}).

This error is indicating that the constraint name of two different foreign keys is duplicated. More info about EntityFrameworkCore's [foreign-key-constraint-name](https://learn.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#foreign-key-constraint-name).

You can customize constraint name of `ParentId` of  `AssetCategory` using `HasConstraintName` fluent api.
```
builder.Entity<AssetCategory>(b =>
{
    b.HasOne(x => x.Parent)
        .WithMany(x => x.Children)
        .HasForeignKey(x => x.ParentId)
        .HasConstraintName("AssetCategory_ParentId");
}
```

**Comment by zhangzw218** [comment]
Thank you. It's up and running
@RayMMond
