### ISSUE TITLE
Add migrations时异常

### ISSUE THREAD

**Issue by baiqiaw** [EasyAbp/EShop#243]
我先安装了ESHOP,然后安装PaymentService，运行 add-migration 异常，项目能正常运行。
异常信息：Method 'get_PaymentItems' in type 'EasyAbp.EShop.Payments.Payments.Payment' from assembly 'EasyAbp.EShop.Payments.Domain, Version=3.5.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by gdlcf88** [comment]
EShop v3.5.0 uses PaymentService v2.4.0
See https://github.com/EasyAbp/EShop/blob/3.5.0/Directory.Build.props#L6

The latest version of PaymentService has breaking changes and was prepared for EShop 4.0.

**Comment by baiqiaw** [comment]
好的，谢谢

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/EShop/pull/245
