### ISSUE TITLE
对象名 'EasyAbpPaymentServicePayments' 无效

### ISSUE THREAD

**Issue by baiqiaw** [EasyAbp/EShop#247]
EShop版本：3.5
PaymentService版本：2.4.0
创建订单成功后，调用/api/e-shop/payments/payment (POST)创建支付时异常，对象名 'EasyAbpPaymentServicePayments' 无效。
项目中已调用
builder.ConfigurePaymentService();
builder.ConfigurePaymentServiceWeChatPay();
builder.ConfigureEShop();

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/EShop/tree/dev/samples
The sample works.

**Comment by baiqiaw** [comment]
仔细比较了示例，除了没有安装预付款模块外，其它的都是一样的，还是找不到这个表
