### ISSUE TITLE
微信支付统一下单异常，签名失败

### ISSUE THREAD

**Issue by baiqiaw** [EasyAbp/EShop#249]
在统一下单接口，未能正常获取到appsetting中的ApiKey配置信息，其它配置能正常获取

**Comment by gdlcf88** [comment]
This has nothing to do with EShop. Please go to https://github.com/EasyAbp/Abp.WeChat.

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/Abp.WeChat/issues/81
