### ISSUE TITLE
CouponType 的注释和实际场景不符合？

### ISSUE THREAD

**Issue by zhangzw218** [EasyAbp/EShop#279]
```
public enum CouponType
{
    /// <summary>
    /// Discount once if the condition is met.
    /// e.g. arrange ConditionAmount = 300 and DiscountAmount = 20.
    /// If the price of a product is 300, the actual order price will be discounted by 20.
    /// </summary>
    Normal = 1,
    
    /// <summary>
    /// Discount every time the condition is met.
    /// e.g. arrange ConditionAmount = 300 and DiscountAmount = 20.
    /// If the price of a product is 300, the actual order price will be discounted by 60.
    /// </summary>
    PerMeet = 2,
    
    /// <summary>
    /// A type of coupon with custom usage rules.
    /// </summary>
    Custom = 4
}
```
先说下，我英语不太好，使用了翻译器，不确定是否理解错误。
Normal  注释上说，满300减20，只减免1次，但实际场景中，我看到的是，没有条件，都减免20.
PerMeet 每次满300都减20，那么测试结果是正确的，但注释不是错了，应该是900减60？

CouponOrderDiscountProvider.cs 我看这里面，Normal没有条件，直接使用 DiscountAmount
```
var totalDiscountedAmount = new Money(
    couponTemplate.CouponType == CouponType.PerMeet
        ? couponTemplate.DiscountAmount *
          Math.Floor(totalOrderLineActualTotalPrice.Amount / couponTemplate.ConditionAmount)
        : couponTemplate.DiscountAmount,
    nodaCurrency, MidpointRounding.ToZero);
```

**Comment by gdlcf88** [comment]
`totalOrderLineActualTotalPrice`是由`orderLinesInScope`产生，后者只会包含符合条件的订单，如果金额不满足要求，不会在此范围内。

PerMeet 的注释错了，是应该改成 900，你可以提交一个 PR 纠正它吗？

**Comment by gdlcf88** [comment]
Sorry，纠正，不是在`orderLinesInScope `中筛选订单项，而是在订单产生时已经筛选过了：https://github.com/EasyAbp/EShop/blob/a52aa4cc1ec81945ba7688d42ca24acde7cbdd22/modules/EasyAbp.EShop.Orders/src/EasyAbp.EShop.Orders.Domain/EasyAbp/EShop/Orders/Orders/NewOrderGenerator.cs#L112

**Comment by zhangzw218** [comment]
我在NewOrerGenerator中，没找到筛选订单的处理。

OrdersAppServiceTests.cs中写了个测试
[InlineData(5, 2.3, 4, 0, CouponType.Normal)]
这个不满足条件，依然触发了满减。
不确定是否我测试写错了，能否帮忙看下？
https://github.com/zhangzw218/EShop/tree/zzw/20240619_4.2.0

**Comment by gdlcf88** [comment]
这是一个 Bug，在 #280 中修复，如果可以把你的 UT 提交到本仓库，会很有帮助。（但是请全英文化，以便长期维护）
