### ISSUE TITLE
[Question] Orders.OrderLine.ProductModificationTime property's usage

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/EShop#51]
What's the point of recording Product(and Detail)ModificationTime in order line?
@gdlcf88 Thanks advance 😄

**Comment by gdlcf88** [comment]
They are recorded for getting the historical version entity, no matter how many times the Product or ProductDetail is updated, its historical version can be queried.

https://github.com/EasyAbp/EShop/blob/8604f53c228d6777894dc76e07ec495ab3860cae/modules/EasyAbp.EShop.Products/src/EasyAbp.EShop.Products.Domain/EasyAbp/EShop/Products/ProductHistories/ProductHistory.cs#L7
https://github.com/EasyAbp/EShop/blob/8604f53c228d6777894dc76e07ec495ab3860cae/modules/EasyAbp.EShop.Products/src/EasyAbp.EShop.Products.Domain/EasyAbp/EShop/Products/ProductDetailHistories/ProductDetailHistory.cs#L7

**Comment by RayMMond** [comment]
Thanks for your reply.
