### ISSUE TITLE
Should use dedicated exception instead of EntityNotFoundException

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/EShop#55]
https://github.com/EasyAbp/EShop/blob/354f1cb5f33fc0dab5061ea59c9b640ab9fef13d/modules/EasyAbp.EShop.Products/src/EasyAbp.EShop.Products.Domain/EasyAbp/EShop/Products/Products/ProductManager.cs#L158-L169

EntityNotFoundException is too vague to identity real problem.

**Comment by gdlcf88** [comment]
You are right.

By the way, ProductDetail is designed to be shareable between different Products and ProductSkus, it is for ProductDetail's reusability, but the sharing mechanism has not been implemented now.
