### ISSUE TITLE
Difference between ParentId and ParentCategoryId in Category model?

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/EShop#63]
1. What's the difference between ParentId and ParentCategoryId in `EasyAbp.EShop.Products.CategoriesCategory`?
1. Which should be used?

**Comment by gdlcf88** [comment]
The `ParentCategoryId` was forgotten to delete in this commit: https://github.com/EasyAbp/EShop/commit/354f1cb5f33fc0dab5061ea59c9b640ab9fef13d

Thank you for reminding me :D

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/EShop/commit/518d3b0b125809bb9f92efc98326d0dfba3654a2
