### ISSUE TITLE
Difference between ProductType and ProductCategory

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/EShop#65]
What's the difference between `ProductType` and `ProductCategory`?

Is `Food/Clothes` a `ProductType` ?

**Comment by gdlcf88** [comment]
If a website has both a general e-shop app and another app that uses the EShop module, there are 2 different way to implement it.

The first way is using microservice: developers build 2 
different apps, both of which have EShop module installed.

But microservice is difficult for many developers, so EShop provide another way to merge them together: create two ProductTypes. So we can distinguish different type of Product and handle the events of them.

**Comment by RayMMond** [comment]
@gdlcf88 thanks for your reply, but I'm still kind of uncertain of the meaning of **Type** from your explanation. 

> If a website has both a general e-shop app and another app that uses the EShop module, they have 2 types of Product.

Did **2 types** in `they have 2 types of Product` refer to product which belong to app1 and product which belong to app2?

Could you please provide some kind of example?

**Comment by gdlcf88** [comment]
For example, a kind of online gift card is on sale, we want the password of the card could be automatically sent to the buyer after the payment is completed. So we can set them as a specified ProductType, and handle the `OrderPaidEto` event and only execute the password sending job for specified type of Product.

It is a solution for complex situations, if we use EShop for a general business, ProductType could be default.

**Comment by RayMMond** [comment]
Got it, thanks a lot.
