### ISSUE TITLE
Add store's owner

### ISSUE THREAD

**Issue by RayMMond** [EasyAbp/EShop#68]
`Store` need a owner id property to manage any store-related permissions.

**Comment by gdlcf88** [comment]
`Store.OwnerUserId` is not enough, maybe it is better to design a `StoreOwner` entity.

Implementing multi-store is a difficult job, there are more problems that should be resolved, such as owners' permissions. I will spend more time thinking about it.

**Comment by gdlcf88** [comment]
We can if the current user is one of the owners of the store, see https://github.com/EasyAbp/EShop/issues/17
