### ISSUE TITLE
EShop as microservice

### ISSUE THREAD

**Issue by volethanh** [EasyAbp/EShop#98]
Hi,

The EShop sample looks great and I just want to ask if you have any plan to integrate the gateway to this EShop. 

And another thing is how the module communicate to each others. I saw in the Order module, you add reference the Product module so that you can call ProductAppService, what should I do if I don't want to add as reference for loose coupling ? 
Or can I add it as nuget package ?

Thanks.

**Comment by gdlcf88** [comment]
> you add reference the Product module so that you can call ProductAppService

Other modules depend only on the **EasyAbp.EShop.Products.Application.Contracts** project and the **EasyAbp.EShop.Products.Domain.Shared** project, which has no services, so I think it is already a loose coupling practice.

The EShop can be deployed as microservice applications, maybe this doc can help: https://docs.abp.io/en/abp/latest/Microservice-Architecture

**Comment by gdlcf88** [comment]
> if you have any plan to integrate the gateway to this EShop.

I'm not sure if I understand what you mean, do you mean you want a demo of EShop's microservices?

I am sorry that I have no practical experience in microservices. I would be very grateful if you are able and willing to provide a microservice sample for EShop. 😄
